Add timeline to rangeslider
calipsa/ui pull request #19
Opened 2021-09-19 19:51 UTC by ben-x

Adds a red marker to sliders.  
This is especially useful for showing where one alarm ends and the other begins.  

<img width="1199" alt="Screenshot 2021-09-19 at 17 22 46" src="https://user-images.githubusercontent.com/16855368/133941002-b0db4374-2e74-4917-b03d-de566c478622.png">

2021-09-21 13:29 UTC, inker requested changes

2021-09-21 13:29 UTC, inker commented on src/components/RangeSlider/Timeline.vue
> +        && value.reduce((acc, v) => acc + v, 0) === 100,
Instead of hardcoding the sum to `100`, why not allow the `timeline` to contain any numbers & be normalised in a computed prop? So `[1, 1, 2]` would be normalised to `[0.25, 0.25, 0.5]`.

Then validation wouldn't be needed (at least the second condition).

2021-09-21 13:29 UTC, inker commented on src/components/RangeSlider/Timeline.vue
> +  top: -6px;
Where does this number come from?

2021-09-21 13:29 UTC, inker commented on src/components/RangeSlider/stories.js
> +  timeline: {
Let's not change the stories for now as I'm in the process of completely refurbishing them & this change will result in conflicts. I'll add this prop once I finish the refurbish.

2021-09-21 13:29 UTC, inker commented on src/components/RangeSlider/index.vue
> +      <Timeline
Has this been tested with `showButtons` set to `true` & `false`?

2021-09-22 10:37 UTC, ben-x commented on src/components/RangeSlider/index.vue
> +      <Timeline
Yes, it has.

2021-09-22 10:39 UTC, ben-x commented on src/components/RangeSlider/Timeline.vue
> +  top: -6px;
Changed to -0.375rem. The trackbar is 0.375rem above the middle of the container, so needed to adjust the timeline to fit this position.

2021-09-22 10:40 UTC, ben-x commented on src/components/RangeSlider/Timeline.vue
> +        && value.reduce((acc, v) => acc + v, 0) === 100,
Created a computed property to normalize the values.

2021-09-24 12:47 UTC, merged